### ISSUE TITLE
DFD Comments October 6

### ISSUE THREAD

**Issue by germonprez** [Pnikiema/ISQA3420PNikiema#18]
Here are some comments. 

Make sure that you only have one DFD in your repository. This one DFD should be represented in the DFD.md file. Right now you have a lot of DFDs. 

1) You are not currently including Software Packages being scanned for NIST vulnerabilities. This would happen in the same area as the license scanning. 

2) Change Software Package License Results Query to Software Package License and Vulnerability Request (this is under the assumption that you get vulnerability results from point 1) into the DB). Also, the Developer needs to be able to make this request too. 

3) You need a data flow leaving the policy data store that returns the policy. In this entire section, you could just have a Request Policy Document going from the Manager (and Developer) to the policy DB. In return, there would be a Policy Document Response going back to both. 

These are good issues to address first. Then you can keep building from there. 

MG

**Comment by Pnikiema** [comment]
Corrections made to DFD and uploaded as a .md file
